[package]
name = "quic-dns"
version = "0.1.0"
edition = "2024"

[features]
# Treat warnings as a build error.
strict = []

[dependencies]
async-executor = "1.13.3"
bytes = "1.11.0"
reqwest = { version = "0.13.1", features = ["http3"]}
rustop = "1.1.4"
tokio = { version = "1.49.0", features = ["net", "rt", "rt-multi-thread", "macros"] }
zeropool = "0.3.1"



[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'
codegen-units = 1
strip = true